### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'freedesktop_os_release'

### ISSUE THREAD

**Issue by victor-perez** [Jip-Hop/jailmaker#32]
After installing on `TrueNAS-SCALE-22.12.3.3` I get this error when I try to create a jail
```
USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.

Install the recommended image (debian bullseye)? [Y/n] y

Enter jail name: portainer

Docker won't be installed by jlmkr.
But it can setup the jail with the capabilities required to run docker.
You can turn DOCKER_COMPATIBLE mode on/off post-install.

Make jail docker compatible right now? [y/N] y

Detected the presence of an intel GPU.

Passthrough the intel GPU? [y/N]
Detected the presence of an nvidia GPU.

Passthrough the nvidia GPU? [y/N] y

WARNING: CHECK SYNTAX

You may pass additional flags to systemd-nspawn.
With incorrect flags the jail may not start.
It is possible to correct/add/remove flags post-install.

Show the man page for systemd-nspawn? [y/N] n
Traceback (most recent call last):
  File "/usr/local/sbin/jlmkr", line 1156, in <module>
    main()
  File "/usr/local/sbin/jlmkr", line 1111, in main
    create_jail(args.name)
  File "/usr/local/sbin/jlmkr", line 828, in create_jail
    raise error
  File "/usr/local/sbin/jlmkr", line 628, in create_jail
    base_os_version = platform.freedesktop_os_release().get('VERSION_CODENAME', release)
AttributeError: module 'platform' has no attribute 'freedesktop_os_release'
```

**Comment by Jip-Hop** [comment]
My bad, I tested the new jlmkr only on the TrueNAS nightlies and those have a newer python version. Thanks for reporting!

**Comment by Jip-Hop** [comment]
Could you try the latest version please?
